# Linear Algebra Introduction

Linear algebra is a representation of linear equations. We can separate the known constants from unknown variables to represent our system of equations. Take the following example, there are three unknowns and three equations

1. $5x_{1}+3x_{2} =1$

2. $x_{1}+2x_{2}+3x_{3} =2$

3. $x_{1}+x_{2}+x_{3} =3$

If we can represent our equations in a matrix-vector format, then we can use standard linear algebra routines to solve for the unknown variables, $x_1,~x_2,~and~x_3.$

Consider the matrix form of equations 1-3 above:

$\left[ \begin{array}{ccc}
5 & 3 & 0 \\
1 & 2 & 3 \\
1 & 1 & 1 \end{array} \right]
\left[\begin{array}{c} 
x_{1} \\ 
x_{2} \\
x_{3}\end{array}\right]=\left[\begin{array}{c} 
1 \\
2 \\
3\end{array}\right]$

$\mathbf{Ax}=\mathbf{b}$

The __matrix__, $\mathbf{A}$ contains all of the constants that are multiplied by our unknown variables $x_1,~x_2,~and~x_3.$ The __vector__, $\mathbf{y}$ contains all of the known constants that are not multiplied by our unknown variables $x_1,~x_2,~and~x_3.$ Finally, the __vector__, $\mathbf{x}=[x_1,~x_2,~x_3]$ contains our unknown values. 

## Exercise

Solve for $x_1,~x_2,~and~x_3.$ How did you approach the problem? Did you use Linear algebra?

Highlight for answers: <font color="white">x1 = 20, x2 = -33, x3 = 16</font>

In [2]:
import numpy as np

In [3]:
A = np.array([[-7,3,0],[7,-19,12],[0,4,-12]])
b = np.array([-20,0,-8])

x = np.linalg.solve(A,b)
for i in range(0,3):
    print('[{:5.1f} {:5.1f} {:5.1f}] {} [{:3.1f}] {} [{:5.1f}]'.format(*A[i],'*',x[i],'=',b[i]))

[ -7.0   3.0   0.0] * [3.9] = [-20.0]
[  7.0 -19.0  12.0] * [2.3] = [  0.0]
[  0.0   4.0 -12.0] * [1.4] = [ -8.0]


We use linear algebra _operations_ to standardize the way we approach a set of equations. If we knew another matrix $\mathbf{A}^{-1}$ that we could multiply both sides of our equation and get a new equation

$\mathbf{A^{-1} A x}= \mathbf{A^{-1} b}$

where $\mathbf{A^{-1} A x} = \mathbf{x}$

then $\mathbf{x} = \mathbf{A^{-1} b}$

if this were a single equation with a single unknown, then we just use the inverse of A as such

$12 x = 6$

$\frac{1}{12} 12 x = \frac{1}{12} 6$

$x=2$

In this notebook, we will look at how to frame our problems as linear algebra problems and work on solve for unknown variables, $\mathbf{x}.$ 

## Example with Mixing Tanks

![Mixing tank volume flow rates](../images/mixing_tanks.png)

In the diagram above we have three tanks of water that are mixing two concentrations of salt water with $5~mg/m^3$ entering tank 1 and $1~mg/m^3$ entering tank three. The outlet is located on the middle tank 2, but the concentration is unknown. 

The volume flow rates of water are shown on each arrow to denote flow in/out of each tank. We want to know what the final concentration at the outlet is $c_2$, but in order to know that we need the concentrations of $c_1~and~c_3$. The mass flow of the salt is the concentration $\times$ volume flow rate. The total mass flow in - mass flow out in each container is 0. We have three mass balance equations

1. $(-7~m^3/s)~c_1 +(3~m^3/s)~c_2 +(4~m^3/s)~5~mg/m^3 = 0$

2. $(7~m^3/s)~c_1 -(3~m^3/s)~c_2 -(4~m^3/s)~c_2 -(12~m^3/s)~c_2 +(12~m^3/s)~c_3 = 0$

3. $(4~m^3/s)~c_2 -(12~m^3/s)~c_3 + (8~m^3/s)~1~mg/m^3 = 0$

or rearranging our mass-balance equations we have

1. $-7c_1+3c_2=-20$

2. $7c_1-19c_2+12c_3=0$

3. $4c_2-12c_3=-8$

We can put this into the same form that we used above with the matrix $\mathbf{A}$ and vectors $\mathbf{x}$ and $\mathbf{b}$

$\left[ \begin{array}{ccc}
-7 & 3 & 0 \\
7 & -19 & 12 \\
0 & 4 & -12 \end{array} \right]
\left[\begin{array}{c} 
c_{1} \\ 
c_{2} \\
c_{3}\end{array}\right]=\left[\begin{array}{c} 
-20 \\
0 \\
-8\end{array}\right]$

$\mathbf{Ax}=\mathbf{b}$

Now, let's use some numpy linear algebra to solve for $c_2$. First, define $\mathbf{A}$ and $\mathbf{b}$ our known constants. 

In [4]:
A=np.array([[-7,3,0],[7,-19,12],[0,4,-12]])
b=np.array([-5,0,-8])
print('matrix A:\t vector b:')
for i in range(0,3):
    print(A[i],'\t',b[i])

matrix A:	 vector b:
[-7  3  0] 	 -5
[  7 -19  12] 	 0
[  0   4 -12] 	 -8


Now, we can solve for $\mathbf{x}$ with the function `np.linalg.solve`. This is an advanced linear algebra solver that incorporates some ideas we will explore in [Module 02](./02_Gauss_elimination.ipynb). For now, we just want to understand the inputs and outputs

```python
x = np.linalg.solve(A,b)
```

In the next cell, we run this line of code. The inputs are the matrix $\mathbf{A}$ and vector $\mathbf{b}$, as defined above as `A` and `b`. The output is our unknown vector $\mathbf{x}=[c_1,~c_2,~c_3]$. If we plug in the values of `x` into our mass balance equations we will see that mass is conserved. 

In [5]:
x = np.linalg.solve(A,b)
print('c1 = {:.2f} mg/m^3,\nc2 = {:.2f} mg/m^3,\nc3 = {:.2f} mg/mm^3'.format(*x))

c1 = 1.18 mg/m^3,
c2 = 1.08 mg/m^3,
c3 = 1.03 mg/mm^3


## Exercise

Show that $\mathbf{Ax} = \mathbf{b}$ in the previous mixing container example. Plug the values of `x` into the three equations and show that mass is conserved. 

In [7]:
np.isclose(A@x, b)

array([ True,  True,  True])

## Vectors 

We use vectors to represent unknown variables or known outputs. In numpy, a vector only has one dimension. 

```python
y = np.array([1,2,3])
```

If you ask for the `shape` of `y`, you get an output of `(3,)`, which means it is a one dimensional vector. 

In [8]:
y=np.array([1,2,3])

y.shape

(3,)

### What's a vector?

Vectors are everywhere: physics, engineering, mathematics, computer science, video games, and more. Each field's interpretation of what a vector *is* may be different, but  vectors live a similar life in every space.

The first episode in the wonderful video series, [_"Essence of Linear Algebra"_](http://3b1b.co/eola) tells you of three different ideas about vectors [1]:

1. For physicists, a vector is an "arrow" of a given length (magnitude) and direction. It can represent directional quantities like velocity, force, acceleration.
2. For computer scientists, a vector is an ordered list of numbers. It can represent a set of variables or features stored in order.
3. For mathematicians, vectors are generic objects that behave a certain way when they are added or scaled:  $\mathbf{u}+\mathbf{v}$, $\alpha\mathbf{v}$.

<img src="../images/whatsavector.png" style="width: 500px;"/> 

#### How you think of a vector depends on what you're doing

In physics, vectors are almost always two- or three-dimensional (although in some fancy branches of physics they do go to higher dimensions). Vectors help physicists describe things like motion and electro-magnetic fields on a plane or in physical 3D space.

But, as we saw in our first example of Linear algebra for a set of equations, the vector could be a set of known or unknown values. This is closer to how vectors are treated in computer science and data science, vectors are often multi-dimensional, that is, they have many components. They contain a set of ordered variables in a data model, like for example: the age, weight, daily hours of sleep, weekly hours of exercise, and blood pressure of an individual (five dimensions).

## Adding and subtracting scaled vectors

In our first linear algebra problem, we had the vector, $\mathbf{x}=[c_1,~c_2,~c_3]$ and solved for $\mathbf{x}=[3.86,~2.33,~1.44]~mg/m^3$. We separated the flow rates out of the equation, but we could also have pulled out the flow rates in three vectors:

$y=Ax=\left[\begin{array}{c} 
-20 \\ 
0 \\
-8\end{array}\right]
=
\left[\begin{array}{c} 
-7 \\ 
7 \\
0\end{array}\right] c_{1}+
\left[\begin{array}{c} 
3 \\ 
-19 \\
4\end{array}\right] c_{2}+
\left[\begin{array}{c} 
0 \\ 
12 \\
-12\end{array}\right] c_{3}$

or 

$\left[\begin{array}{c} 
-20 \\ 
0 \\
-8\end{array}\right]
=
\left[\begin{array}{c} 
-7 \\ 
7 \\
0\end{array}\right] 3.86+
\left[\begin{array}{c} 
3 \\ 
-19 \\
4\end{array}\right] 2.33+
\left[\begin{array}{c} 
0 \\ 
12 \\
-12\end{array}\right] 1.44 = 
\left[\begin{array}{c} 
-20 \\ 
0 \\
-8\end{array}\right]$

When you multiply a vector by a scalar (something with a single magnitude, a number) the result is that each component of the vector is multiplied by that scalar. That's why we can separate the flow rates and multiply them by the individual concentrations and add the results. 

$y = a_{1}x_{1} + a_{2}x_{2} +...+a_{N}x_{N}$

- $a_{i}$ is a column vector 

- $x_{i}$ is a scalar taken from the $i^{th}$ element of x.

Multiplying a vector by a scalar is the same as multiplying each component of the vector by the scalar. So if we multiply a vector $\mathbf{a}$ by 2, then it is the same as multiplying each component, $a_i$ by 2. 

$2\mathbf{a}=\left[\begin{array}{c} 
2a_{1} \\ 
2a_{2} \\
\vdots \\
2a_{n}\end{array}\right]$

In [8]:
a1 = np.array([-7,7,0])
a2 = np.array([3,-19,4])
a3 = np.array([0,12,-12])

out = x[0]*a1+x[1]*a2+x[2]*a3

print('external inputs')
print('flow in at 1: {:.1f} g/s\nflow in at 2: {:.1f} g/s\nflow in at 3: {:.1f} g/s'.format(*out*-1))

external inputs
flow in at 1: 5.0 g/s
flow in at 2: -0.0 g/s
flow in at 3: 8.0 g/s


## Representation of a problem with Matrices and Vectors

There are two main types of problems that are solved with linear algebra. Let's use the following variables to describe our problems. 

- $\mathbf{y}:$ a set of known outputs, $y_{1},~y_{2},~...y_{N}$ 

- $\mathbf{A}:$ a set of known constants from equations, $A=\left[ \begin{array}{cccc}
A_{11} & A_{12} &...& A_{1N} \\
A_{21} & A_{22} &...& A_{2N} \\
\vdots & \vdots &\ddots& \vdots \\
A_{M1} & A_{M2} &...& A_{MN}\end{array} \right]$

- $\mathbf{x}:$a set of unknown inputs, $x_{1},~x_{2},~...x_{N}$

- $\lambda:$ an unknown constant

Using the variables defined above we describe the two main types of linear algebra problems:

1. linear system solutions where $\mathbf{Ax} = \mathbf{b}$

2. eigenvalue soslutions where $\mathbf{Ax} = \lambda \mathbf{x}$

We saw an example of the first type, in the mixing example. Eigenvalue problems come up in a number of engineering and science applications. We will cover the application of eigenvalues in the last module when we look at boundary value problems. We will restrict our initial applications of linear algebra to linear systems. 

# 1. Another linear system solution

![Example of Applying Newton's second law to obtain a linear system](../images/mass-pulley.png)

In the above diagram, there are 4 masses, connected by 4 cords. Our goal is to create a system of equations that are solveable with Linear Algebra. We start with Newton's second law to determine 4 equations of motion

1. $m_1 a_1 = T_1 + \mu m_1g\cos\theta - m_1g\sin\theta$

2. $m_2 a_2 = T_2 -T_1 + \mu m_2g\cos\theta - m_2g\sin\theta$

3. $m_3 a_3 = T_3 -T_2 + \mu m_3g\cos\theta - m_3g\sin\theta$

4. $m_4 a_4 = T_3 - m_4g$

This gives us four equations with 7 unknowns $(a_1,~a_2,~a_3,~a_4,~T_1,~T_2,~and~T_3).$ We also have 3 constraints that relate the motion of masses 1-4:

1. $a_1 = a_2$

2. $a_2 = a_3$

3. $-a_3 = a_4$

So we can limit our description of acceleration to just $a$, because the system only has one overall degree of freedom (as long as the connecting cords remain taut). Now we have four equations and four unknowns $(a,~T_1,~T_2,~and~T_3).$

1. $-m_1 a - T_1 = \mu m_1g\cos\theta - m_1g\sin\theta$

2. $-m_2 a - T_2 +T_1 = \mu m_2g\cos\theta - m_2g\sin\theta$

3. $-m_3 a - T_3 +T_2 = \mu m_3g\cos\theta - m_3g\sin\theta$

4. $m_4 a - T_3  = - m_4g$

or in the matrix-vector form:

$\left[ \begin{array}{cccc}
-m_1 & -1 & 0 & 0 \\
-m_2 & 1 & -1 & 0\\
-m_3 & 0 & 1 & -1\\
m_4 & 0 & 0 & -1\end{array} \right]
\left[\begin{array}{c} 
a \\ 
T_1 \\
T_2 \\
T_{3}\end{array}\right]=\left[\begin{array}{c} 
\mu m_1g\cos\theta - m_1g\sin\theta\\
\mu m_2g\cos\theta - m_2g\sin\theta\\
 \mu m_3g\cos\theta - m_3g\sin\theta\\
- m_4g\end{array}\right]$

$\mathbf{Ax}=\mathbf{b}$

Let's use the following constants to solve for acceleration and tensions:

* $\mu = 0.2$
* $m_1 = m_2 = m_3 = 2~kg$
* $m_4 = 1~kg$
* $\theta=\dfrac{\pi}{4}=45^o$

In [9]:
mu = 0.1
m1=m2=m3=2
m4=1
g =9.81
a = np.pi/4

A2 = np.array([[-m1,-1,0,0],[-m2,1,-1,0],[-m3,0,1,-1],[m4,0,0,-1]])
y2 = np.array([mu*m1*g*np.cos(a)-m1*g*np.sin(a),\
               mu*m2*g*np.cos(a)-m2*g*np.sin(a),\
               mu*m3*g*np.cos(a)-m3*g*np.sin(a),\
               -m4*g])

print('A2 = \t\t y2=')
for i in range(0,4):
    print(A2[i],'\t',y2[i])

A2 = 		 y2=
[-2 -1  0  0] 	 -12.486091542192055
[-2  1 -1  0] 	 -12.486091542192055
[-2  0  1 -1] 	 -12.486091542192055
[ 1  0  0 -1] 	 -9.81


In [10]:
x2 = np.linalg.solve(A2,y2)

print('a={:.2f} m/s/s\nT1={:.1f} N\nT2={:.1f} N\nT3={:.1f} N'.format(*x2))

a=3.95 m/s/s
T1=4.6 N
T2=9.2 N
T3=13.8 N




## Exercise

1. Plug in the values that we solved into the original 4 equations. Show that our values for accelerations and tensions satisfy our initial equations. 

2. Create a new vector `y3` where the coefficient of friction is $\mu=0.5$ what is the new acceleration? Do the tensions increase or decrease when tension increases?

In [13]:
# Ex 1
np.isclose(A2@x2, y2)

array([ True,  True,  True,  True])

In [16]:
# Ex 2
mu = 0.5
y3 = np.array([mu*m1*g*np.cos(a)-m1*g*np.sin(a),\
               mu*m2*g*np.cos(a)-m2*g*np.sin(a),\
               mu*m3*g*np.cos(a)-m3*g*np.sin(a),\
               -m4*g])

x3 = np.linalg.solve(A2,y3)

print('a = {}'.format(x3[0]))

print('Tensions increase by x', x2[1:]/x3[1:])

a = 1.571450367188584
Tensions increase by x [1.2089631 1.2089631 1.2089631]


## Pause and ponder

In this example, the unknown vector, $\mathbf{x}=[a,~T_1,~T_2,~T_3],$ is a combination of acceleration and forces. This definition of a vector is less intuitive than a physics-based magnitude and direction, but it is __extremely__ useful in solving engineering and physics problems. Here are a few __key ideas__ from these two linear system exercises:

* In order to solve for $n$ unknowns, we need $n$ independent equations 
* A vector is a collection of numbers that we either know or want to know
* A matrix is a collection of known numbers _note: there are some cases where you might want to solve for a matrix, but for now let's restrict our use of linear algebra to known matrices_

The specification of _independent equations_ is best illustrated using _dependent_ equations:

1. $x+y = 3$

2. $2x+2y=6$



# What we've learned

* How to solve a linear algebra problem with `np.linalg.solve`
* Creating a linear system of equations
* Identify constants in a linear system $\mathbf{A}$ and $\mathbf{b}$
* Identify unknown variables in a linear system $\mathbf{x}$



# References

1. Chapra, Steven _Applied Numerical Methods with Matlab for Engineers._ __ch 8.__ McGraw Hill. 

2. Kiusalaas, Jaan _Numerical Methods in Engineering with Python 3._ __ch 2.__ Cambridge University Press. 

3. [_"Essence of Linear Algebra"_](http://3b1b.co/eola) 3 Blue 1 Brown Linear algebra series. 

# Problems

1. Consider 4 masses connected in series to 4 springs with K=1,000 N/m. What are the final positions of the masses i.e. when acceleration is 0? 

![Springs-masses](../images/mass_springs.png)

The masses haves the following amounts, $g=9.81~m/s^2,~m_1=1,~m_2=2,~m_3=3,~and~m_4=4 kg.$ Using a FBD for each mass:

$m_{1}g+k(x_{2}-x_{1})-kx_{1}=0$

$m_{2}g+k(x_{3}-x_{2})-k(x_{2}-x_{1})=0$

$m_{3}g+k(x_{4}-x_{3})-k(x_{3}-x_{2})=0$

$m_{4}g-k(x_{4}-x_{3})=0$

in matrix form:

$\left[ \begin{array}{cccc}
2k & -k & 0 & 0 \\
-k & 2k & -k & 0 \\
0 & -k & 2k & -k \\
0 & 0 & -k & k \end{array} \right]
\left[ \begin{array}{c}
x_{1} \\
x_{2} \\
x_{3} \\
x_{4} \end{array} \right]=
\left[ \begin{array}{c}
m_{1}g \\
m_{2}g \\
m_{3}g \\
m_{4}g \end{array} \right]$

In [19]:
k = 1000
K = np.array([[2*k, -k, 0, 0], 
              [-k, 2*k, -k, 0],
              [0, -k, 2*k, -k],
              [0, 0, -k, k]])
yP = np.array([m1, m2, m3, m4])*9.81 

xP = np.linalg.solve(K,yP)

print(xP)
    

[0.06867 0.11772 0.14715 0.15696]
